// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://olzysjwkbkyvqdbwfiwi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9senlzandrYmt5dnFkYndmaXdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMDI5NTcsImV4cCI6MjA3MTg3ODk1N30.g7CJOhW-7DRRCAdlp9WVn50OSKzpU1_kmbh9w7Yy2Ms";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});